Task bot 2417 implement rail section
CanalTP/Chaos pull request #461
Opened 2021-01-29 15:48 UTC by kun2985

# Description

This PR implement rail section

## Issue (optional)

Issue link: bot-2417

2021-02-01 13:09 UTC, pthegner commented on migrations/versions/5bf2d2bc5cb_add_rail_section.py
> +    op.execute("DELETE FROM pt_object WHERE  type='rail_section'")
```suggestion
    op.execute("DELETE FROM pt_object WHERE type='rail_section'")
```

2021-02-02 15:53 UTC, Fahmus commented on chaos/db_helper.py
> +    :param pt_object_json: Flux which contains json information of pt_object
```suggestion
    :param pt_object_json: Flux which contains json information of ordered pt_object
```

2021-02-02 16:07 UTC, tchevily commented on chaos/db_helper.py
> +                except exceptions.ObjectUnknown as xxx_todo_changeme:
Wich kind of changes are you waiting with "xxx_todo_changeme"

2021-02-02 16:11 UTC, tchevily commented on chaos/db_helper.py
> +def fill_and_add_rail_section(navitia, all_objects, pt_object_json):
This function is too long. You should refactor it.

2021-02-02 16:22 UTC, tchevily requested changes

2021-02-02 16:22 UTC, tchevily commented on tests/populate_pb_test.py
> -def test_disruption_without_routes():
Why was this test deleted ?

2021-02-02 16:24 UTC, tchevily requested changes
Functional tests are missing

2021-02-03 08:31 UTC, pthegner commented on tests/populate_pb_test.py
> -def test_disruption_without_routes():
next test seems to be a duplicate of this one.

2021-02-04 08:43 UTC, pthegner commented on chaos/db_helper.py
> +                json['id']))
```suggestion
            "{} '{}' doesn't exist".format(
                json['type'],
                json['id']))
```

2021-02-05 14:55 UTC, tchevily approved these changes

2021-02-09 16:38 UTC, Fahmus approved these changes

2021-02-16 13:58 UTC, Msaglier approved these changes

2021-02-16 13:59 UTC, merged