db_helper minor PEP8 resolutions
CanalTP/Chaos pull request #510
Opened 2022-01-19 21:02 UTC by dvdn

2022-01-25 16:51 UTC, pthegner commented
```
IntegrityError: (IntegrityError) insert or update on table "impact" violates foreign key constraint "impact_disruption_id_fkey"
DETAIL:  Key (disruption_id)=(a750994c-01fe-11e4-b4fb-080027079ff3) is not present in table "disruption".
 'INSERT INTO impact (created_at, updated_at, id, status, disruption_id, severity_id, send_notifications, version, notification_date) VALUES (%(created_at)s, %(updated_at)s, %(id)s, %(status)s, %(disruption_id)s, %(severity_id)s, %(send_notifications)s, %(version)s, %(notification_date)s)' {'status': 'published', 'disruption_id': 'a750994c-01fe-11e4-b4fb-080027079ff3', 'notification_date': None, 'created_at': datetime.datetime(2022, 1, 19, 22, 22, 56), 'severity_id': '7ffab232-3d48-4eea-aa2c-22f8680230b6', 'send_notifications': False, 'updated_at': None, 'version': 1, 'id': '59e5d3a1-7976-11ec-a500-0242ac120003'}
```

2022-02-07 15:24 UTC, tchevily approved these changes

2022-02-08 07:30 UTC, pthegner approved these changes

2022-02-08 16:17 UTC, Msaglier requested changes
Only happens for past dates.

2022-02-09 09:08 UTC, Msaglier approved these changes

2022-02-09 13:06 UTC, merged